services:
  - type: web
    name: remonal
    env: python
    plan: free
    pythonVersion: 3.13
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 sojibWebApp.wsgi:application
    preDeployCommand: python manage.py migrate
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        value: "django-insecure-render-production-key-change-this"
